const { Usuario, UsuarioSchema } = require('./usuario');
const { Rol, RolSchema } = require('./rol');
const { Persona, PersonaSchema } = require('./persona');
const { Pais, PaisSchema } = require('./pais');
const { Estado, EstadoSchema } = require('./estado');
const { Municipio, MunicipioSchema } = require('./municipio');
const { Domicilio, DomicilioSchema } = require('./domicilio');
const { Institucion, InstitucionSchema } = require('./institucion');
const { Plantel, PlantelSchema } = require('./plantel');
const { Academia, AcademiaSchema } = require('./academia');
const { AlumnoObservacion, AlumnoObservacionSchema } = require('./alumnoObservacion');
const { Ciclo, CicloSchema } = require('./ciclo');
const { TipoSolicitud, TipoSolicitudSchema } = require('./tipoSolicitud');
const { EstatusSolicitud, EstatusSolicitudSchema } = require('./estatusSolicitud');
const { Evaluador, EvaluadorSchema } = require('./evaluador');
const { Nivel, NivelSchema } = require('./nivel');
const { Modalidad, ModalidadSchema } = require('./modalidad');
const { Solicitud, SolicitudSchema } = require('./solicitud');
const { Programa, ProgramaSchema } = require('./programa');
const { Cumplimiento, CumplimientoSchema } = require('./cumplimiento');
const { ProgramaEvaluacion, ProgramaEvaluacionSchema } = require('./programaEvaluacion');
const { EdificioNivel, EdificioNivelSchema } = require('./edificioNivel');
const { PlantelEdificioNivel, PlantelEdificioNivelSchema } = require('./plantelEdificioNivel');
const { Higiene, HigieneSchema } = require('./Higiene');
const { PlantelHigiene, PlantelHigieneSchema } = require('./PlantelHigiene');
const { SeguridadSistema, SeguridadSistemaSchema } = require('./SeguridadSistema');
const { PlantelSeguridadSistema, PlantelSeguridadSistemaSchema } = require('./PlantelSeguridadSistema');
const { Turno, TurnoSchema } = require('./turno');
const { ProgramaTurno, ProgramaTurnoSchema } = require('./ProgramaTurno');
const { SolicitudUsuario, SolicitudUsuarioSchema } = require('./SolicitudUsuario');
const { TipoInstalacion, TipoInstalacionSchema } = require('./TipoInstalacion');
const { Infraestructura, InfraestructuraSchema } = require('./Infraestructura');


function setupModels(sequelize) {
  Usuario.init(UsuarioSchema, Usuario.config(sequelize));
  Rol.init(RolSchema, Rol.config(sequelize));
  Persona.init(PersonaSchema, Persona.config(sequelize));
  Pais.init(PaisSchema, Pais.config(sequelize));
  Estado.init(EstadoSchema, Estado.config(sequelize));
  Municipio.init(MunicipioSchema, Municipio.config(sequelize));
  Domicilio.init(DomicilioSchema, Domicilio.config(sequelize));
  Institucion.init(InstitucionSchema, Institucion.config(sequelize));
  Plantel.init(PlantelSchema, Plantel.config(sequelize));
  Academia.init(AcademiaSchema, Academia.config(sequelize));
  AlumnoObservacion.init(AlumnoObservacionSchema, AlumnoObservacion.config(sequelize));
  Ciclo.init(CicloSchema, Ciclo.config(sequelize));
  EstatusSolicitud.init(EstatusSolicitudSchema, EstatusSolicitud.config(sequelize));
  TipoSolicitud.init(TipoSolicitudSchema, TipoSolicitud.config(sequelize));
  Solicitud.init(SolicitudSchema, Solicitud.config(sequelize));
  Modalidad.init(ModalidadSchema, Modalidad.config(sequelize));
  Evaluador.init(EvaluadorSchema, Evaluador.config(sequelize));
  Nivel.init(NivelSchema, Nivel.config(sequelize));
  Programa.init(ProgramaSchema, Programa.config(sequelize));
  Cumplimiento.init(CumplimientoSchema, Cumplimiento.config(sequelize));
  ProgramaEvaluacion.init(ProgramaEvaluacionSchema, ProgramaEvaluacion.config(sequelize));
  EdificioNivel.init(EdificioNivelSchema, EdificioNivel.config(sequelize));
  PlantelEdificioNivel.init(PlantelEdificioNivelSchema, PlantelEdificioNivel.config(sequelize));
  Higiene.init(HigieneSchema, Higiene.config(sequelize));
  PlantelHigiene.init(PlantelHigieneSchema, PlantelHigiene.config(sequelize));
  SeguridadSistema.init(SeguridadSistemaSchema, SeguridadSistema.config(sequelize));
  PlantelSeguridadSistema.init(PlantelSeguridadSistemaSchema, PlantelSeguridadSistema.config(sequelize));
  Turno.init(TurnoSchema, Turno.config(sequelize));
  ProgramaTurno.init(ProgramaTurnoSchema, ProgramaTurno.config(sequelize));
  SolicitudUsuario.init(SolicitudUsuarioSchema, SolicitudUsuario.config(sequelize));
  TipoInstalacion.init(TipoInstalacionSchema, TipoInstalacion.config(sequelize));
  Infraestructura.init(InfraestructuraSchema, Infraestructura.config(sequelize));

  Usuario.associate(sequelize.models);
  Rol.associate(sequelize.models);
  Persona.associate(sequelize.models);
  Pais.associate(sequelize.models);
  Estado.associate(sequelize.models);
  Municipio.associate(sequelize.models);
  Domicilio.associate(sequelize.models);
  Institucion.associate(sequelize.models);
  Plantel.associate(sequelize.models);
  Academia.associate(sequelize.models);
  AlumnoObservacion.associate(sequelize.models);
  Ciclo.associate(sequelize.models);
  TipoSolicitud.associate(sequelize.models);
  EstatusSolicitud.associate(sequelize.models);
  Solicitud.associate(sequelize.models);
  Modalidad.associate(sequelize.models);
  Evaluador.associate(sequelize.models);
  Nivel.associate(sequelize.models);
  Programa.associate(sequelize.models);
  Cumplimiento.associate(sequelize.models);
  ProgramaEvaluacion.associate(sequelize.models);
  EdificioNivel.associate(sequelize.models);
  PlantelEdificioNivel.associate(sequelize.models);
  Higiene.associate(sequelize.models);
  PlantelHigiene.associate(sequelize.models);
  SeguridadSistema.associate(sequelize.models);
  PlantelSeguridadSistema.associate(sequelize.models);
  Turno.associate(sequelize.models);
  ProgramaTurno.associate(sequelize.models);
  SolicitudUsuario.associate(sequelize.models);
  TipoInstalacion.associate(sequelize.models);
  Infraestructura.associate(sequelize.models);
}

module.exports = setupModels;
